import type { ProvinceId } from './provinces';

/**
 * 每省一条（或以上）独立主路线：primary 必须互不抢唯一归属。
 * also 仅表示途经，不能代替该省自己的 primary。
 */
export const routeProvinces: Record<
  string,
  { primary: ProvinceId; also?: ProvinceId[] }
> = {
  // 华北
  'mutianyu-day': { primary: 'beijing' },
  'gubei-overnight': { primary: 'beijing' },
  'tianjin-day': { primary: 'tianjin' },
  'chengde-2d': { primary: 'hebei' },
  'huabei-hebei-beidaihe': { primary: 'hebei' },
  'huabei-hebei-zhangjiakou': { primary: 'hebei' },
  'huabei-hebei-baoding': { primary: 'hebei' },
  'huabei-hebei-tangshan': { primary: 'hebei' },
  'huabei-hebei-shijiazhuang': { primary: 'hebei' },
  'huabei-shanxi-loop': { primary: 'shanxi' },
  'huabei-shanxi-pingyao-deep': { primary: 'shanxi' },
  'huabei-neimeng-summer': { primary: 'neimenggu' },
  'huabei-neimeng-hulunbuir': { primary: 'neimenggu' },
  'huabei-shandong-coast': { primary: 'shandong' },
  'huabei-shandong-yantai': { primary: 'shandong' },
  'huabei-shandong-taishan': { primary: 'shandong' },
  // 东北
  'dongbei-dalian-summer': { primary: 'liaoning' },
  'dongbei-liaoning-shenyang': { primary: 'liaoning' },
  'dongbei-changbai-summer': { primary: 'jilin' },
  'dongbei-jilin-yanbian': { primary: 'jilin' },
  'dongbei-harbin-snow-3d': { primary: 'heilongjiang' },
  'dongbei-heilongjiang-wudalianchi': { primary: 'heilongjiang' },
  // 华东
  'huadong-shanghai-short': { primary: 'shanghai' },
  'huadong-suzhou-nanjing': { primary: 'jiangsu' },
  'huadong-jiangsu-yangzhou': { primary: 'jiangsu' },
  'huadong-hangzhou-suzhou': { primary: 'zhejiang' },
  'huadong-suhan-slow': {
    primary: 'zhejiang',
    also: ['jiangsu', 'anhui'],
  },
  'huadong-huangshan-hui': { primary: 'anhui' },
  'huadong-wuyuan-spring': { primary: 'jiangxi' },
  // 华中
  'huazhong-luoyang-kaifeng': { primary: 'henan' },
  'huazhong-wudang-3d': { primary: 'hubei' },
  'huazhong-yichang-three-gorges': { primary: 'hubei' },
  'huazhong-zhangjiajie': { primary: 'hunan' },
  'huazhong-hunan-changsha': { primary: 'hunan' },
  'huazhong-xian-slow': { primary: 'shaanxi' },
  'huazhong-shaanxi-hanzhong': { primary: 'shaanxi' },
  // 华南
  'huanan-xiamen-winter': { primary: 'fujian' },
  'huanan-fujian-quanzhou': { primary: 'fujian' },
  'huanan-guangzhou-chaoshan': { primary: 'guangdong' },
  'huanan-zhuhai-3d': { primary: 'guangdong' },
  'huanan-guilin-yangshuo': { primary: 'guangxi' },
  'huanan-guangxi-detian': { primary: 'guangxi' },
  'huanan-sanya-winter': { primary: 'hainan' },
  'huanan-hainan-slow-west': { primary: 'hainan' },
  // 西南
  'xinan-chongqing-slow': { primary: 'chongqing' },
  'xinan-chengdu-slow': { primary: 'sichuan' },
  'xinan-dujiangyan-2d': { primary: 'sichuan' },
  'xinan-chuanxi-slow': { primary: 'sichuan' },
  'xinan-guizhou-loop': { primary: 'guizhou' },
  'xinan-guizhou-zhenyuan': { primary: 'guizhou' },
  'yunnan-dali-lijiang': { primary: 'yunnan' },
  'yunnan-xishuangbanna-winter': { primary: 'yunnan' },
  'yunnan-dianxi-tengchong': { primary: 'yunnan' },
  // 西北 / 青藏
  'compose-hexi-dunhuang-zhangye': { primary: 'gansu' },
  'leg-dunhuang-mogao': { primary: 'gansu' },
  'leg-zhangye-danxia': { primary: 'gansu' },
  'xibei-lanzhou-xiahe': { primary: 'gansu' },
  'xibei-ningxia-3d': { primary: 'ningxia' },
  'xibei-ningxia-shapotou': { primary: 'ningxia' },
  'xibei-xinjiang-north': { primary: 'xinjiang' },
  'xibei-xinjiang-yili': { primary: 'xinjiang' },
  'compose-nanjiang-kuqa-kashi': { primary: 'xinjiang' },
  'leg-kuqa-canyon': { primary: 'xinjiang' },
  'xibei-xinjiang-kashi': { primary: 'xinjiang' },
  'base-kashi': { primary: 'xinjiang' },
  'xibei-xinjiang-turpan': { primary: 'xinjiang' },
  'xibei-xinjiang-duku': { primary: 'xinjiang' },
  'qingzang-qinghai-lake': { primary: 'qinghai' },
  'qingzang-xining-3d': { primary: 'qinghai' },
  'qingzang-qilian-optional': { primary: 'qinghai' },
  'qingzang-lhasa-slow': { primary: 'xizang' },
  'qingzang-shigatse-taste': { primary: 'xizang' },
  // 全国大环线（跨省；primary 为枢纽省，also 途经）
  'national-qinggan-slow': {
    primary: 'qinghai',
    also: ['gansu'],
  },
  'national-silkroad-slow': {
    primary: 'gansu',
    also: ['shaanxi', 'xinjiang'],
  },
  'national-chuandian-slow': {
    primary: 'yunnan',
    also: ['sichuan'],
  },
  // 边陲城市
  'frontier-dandong': { primary: 'liaoning' },
  'frontier-manzhouli': { primary: 'neimenggu' },
  'frontier-mohe': { primary: 'heilongjiang' },
  'frontier-erlian': { primary: 'neimenggu' },
  'frontier-dongxing': { primary: 'guangxi' },
  'frontier-ruili': { primary: 'yunnan' },
  // 长居推荐（城市基地）；yangshuo/zhenyuan 已降级为名景短腿，id 保留
  'longstay-dali': { primary: 'yunnan' },
  'longstay-kunming': { primary: 'yunnan' },
  'longstay-yangshuo': { primary: 'guangxi' },
  'longstay-weihai': { primary: 'shandong' },
  'longstay-hulunbuir': { primary: 'neimenggu' },
  'longstay-dujiangyan': { primary: 'sichuan' },
  'longstay-zhenyuan': { primary: 'guizhou' },
  'longstay-hainan-east': { primary: 'hainan' },
  // coverage wave 20260802
  'huazhong-hubei-wuhan': { primary: 'hubei' },
  'huazhong-henan-zhengzhou': { primary: 'henan' },
  'huadong-anhui-hefei': { primary: 'anhui' },
  'huanan-fujian-fuzhou': { primary: 'fujian' },
  'huadong-jiangxi-nanchang': { primary: 'jiangxi' },
  'huabei-shanxi-taiyuan': { primary: 'shanxi' },
  'huanan-guangdong-shenzhen': { primary: 'guangdong' },
  'huabei-shandong-jinan': { primary: 'shandong' },
  'dongbei-jilin-changchun': { primary: 'jilin' },
  'huadong-jiangsu-nanjing': { primary: 'jiangsu' },
  'xinan-guizhou-guiyang': { primary: 'guizhou' },
  'huanan-guangxi-nanning': { primary: 'guangxi' },
  'huanan-hainan-haikou': { primary: 'hainan' },
  'xinan-yunnan-kunming-city': { primary: 'yunnan' },
  'qingzang-nyingchi-slow': { primary: 'xizang' },
  'qingzang-g318-lhasa-nyingchi': { primary: 'xizang' },
  'xinan-sichuan-g318-east': { primary: 'sichuan' },
  'huadong-jiangnan-water-towns': { primary: 'zhejiang', also: ['jiangsu', 'shanghai'] },
  'xinan-sichuan-leshan-emei': { primary: 'sichuan' },
  'dongbei-heilongjiang-harbin-summer': { primary: 'heilongjiang' },
  'huabei-neimeng-hohhot': { primary: 'neimenggu' },
  // coverage wave 20260802b
  'huadong-jiangsu-wuxi': { primary: 'jiangsu' },
  'huadong-zhejiang-ningbo': { primary: 'zhejiang' },
  'huanan-guangdong-dongguan': { primary: 'guangdong' },
  'huanan-guangdong-foshan': { primary: 'guangdong' },
  'qingzang-g214-xining-taste': { primary: 'qinghai' },
  'huazhong-shaanxi-g210-yanan': { primary: 'shaanxi' },
  'huabei-beijing-city-slow': { primary: 'beijing' },
  'qingzang-railway-slow': { primary: 'xizang', also: ['qinghai'] },
  // coverage wave 20260802c
  'national-jinghu-coast-slow': {
    primary: 'shanghai',
    also: ['tianjin', 'shandong', 'jiangsu'],
  },
  'yunnan-g214-shangri-la-taste': { primary: 'yunnan' },
  // Yunnan cross-border corridor (Hekou→Sapa); primary remains Yunnan anchor
  'yunnan-hekou-sapa-corridor': { primary: 'yunnan' },
  // Famous stitch 20260802 (new ids; wuyuan/xiamen/leshan overwrite keep keys)
  'xinan-sichuan-jiuzhaigou': { primary: 'sichuan' },
  'huazhong-hunan-fenghuang': { primary: 'hunan' },
  'xibei-xinjiang-urumqi-city': { primary: 'xinjiang' },
  'huadong-jiangxi-lushan': { primary: 'jiangxi' },
  'huadong-zhejiang-shaoxing': { primary: 'zhejiang' },
  'huabei-shanxi-wutai': { primary: 'shanxi' },
  // Famous P1 20260802 (taishan overwrite keeps key)
  'huanan-fujian-wuyi': { primary: 'fujian' },
  'huanan-guangxi-beihai': { primary: 'guangxi' },
  'huadong-zhejiang-putuo': { primary: 'zhejiang' },
  'huanan-guangdong-kaiping': { primary: 'guangdong' },
  'huanan-guangdong-danxia': { primary: 'guangdong' },
  'huadong-anhui-jiuhua': { primary: 'anhui' },
  'huadong-zhejiang-qiandao': { primary: 'zhejiang' },
  'xinan-chongqing-wulong': { primary: 'chongqing' },
  'xinan-guizhou-huangguoshu': { primary: 'guizhou' },
  'huadong-jiangsu-changzhou': { primary: 'jiangsu' },
  'huadong-zhejiang-wenzhou': { primary: 'zhejiang' },
  'huanan-guangdong-huizhou': { primary: 'guangdong' },
  // Famous P2 20260802 (pingyao overwrite keeps key)
  'xinan-guizhou-fanjing': { primary: 'guizhou' },
  'xinan-guizhou-libo': { primary: 'guizhou' },
  'huazhong-hubei-shennongjia': { primary: 'hubei' },
  'huazhong-hubei-enshi': { primary: 'hubei' },
  'xinan-guizhou-dong-corridor': { primary: 'guizhou' },
  'huanan-guangdong-zhongshan': { primary: 'guangdong' },
  'xibei-gansu-lanzhou-huanghe': { primary: 'gansu' },
  'huanan-guangdong-chaoshan': { primary: 'guangdong' },
  'xinan-sichuan-g318-mid': { primary: 'sichuan' },
  // Prefecture wave 20260802d
  'huazhong-henan-luoyang-county': { primary: 'henan' },
  'huazhong-henan-kaifeng': { primary: 'henan' },
  'huadong-jiangsu-suzhou-county': { primary: 'jiangsu' },
  'xinan-yunnan-dali-daytrips': { primary: 'yunnan' },
  // Prefecture / famous gap wave 20260802e
  'huabei-shanxi-xinzhou-county': { primary: 'shanxi' },
  'huadong-jiangsu-yangzhou-county': { primary: 'jiangsu' },
  'huadong-jiangsu-zhenjiang': { primary: 'jiangsu' },
  'huabei-neimeng-aershan': { primary: 'neimenggu' },
  'huazhong-henan-anyang': { primary: 'henan' },
  'huazhong-henan-jiaozuo': { primary: 'henan' },
  'huadong-jiangsu-nantong': { primary: 'jiangsu' },
  'huadong-zhejiang-jiaxing': { primary: 'zhejiang' },
  'huadong-zhejiang-huzhou': { primary: 'zhejiang' },
  'huazhong-hunan-yueyang': { primary: 'hunan' },
  'huabei-hebei-handan': { primary: 'hebei' },
  // Prefecture wave 20260802f
  'huabei-shanxi-yuncheng': { primary: 'shanxi' },
  'huabei-shanxi-linfen': { primary: 'shanxi' },
  'huabei-shandong-weifang': { primary: 'shandong' },
  'huazhong-hubei-jingzhou': { primary: 'hubei' },
  'huadong-anhui-xuancheng': { primary: 'anhui' },
};
