import type { Route } from '../types';

/**
 * Coverage wave 2026-08-02: tier-1/new-tier-1 gaps + Tibet 林芝/G318 + corridors.
 * Evidence: research/notes/multi-discovery/* + coverage-gap-matrix-20260802.md
 */
export const patchRoutes: Route[] = [
  {
    id: 'huazhong-hubei-wuhan',
    title: '武汉 · 东湖黄鹤楼慢游',
    region: 'huazhong',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约4–6天',
    transport: '北京西/丰台高铁至武汉站/汉口/武昌约4–5小时，或飞天河；市内地铁+打车；东湖可观光车/电瓶车。结束后高铁或飞回北京',
    budgetLabel: '本趟约2800–4800元（高铁/机票+电梯酒店；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Yellow_Crane_Tower_61469-Wuhan_%2849149984218%29.jpg/1280px-Yellow_Crane_Tower_61469-Wuhan_%2849149984218%29.jpg',
    summary: '湖北省会补线：武昌黄鹤楼量力浅登或远观，东湖绿道电瓶车减步，省博室内看展；江汉路平地浅逛。夏酷热改室内与早晚；勿与武当/三峡同趟特种兵。',
    introduction: '武汉市辖江岸/武昌/洪山等区。爸妈优先近地铁电梯酒店为锚，黄鹤楼与东湖分日，省博作空调日。\n\n黄鹤楼台阶与排队量大，腿脚紧可园区平路+远观。东湖绿道优先电瓶车/观光车，勿硬骑全程。不排木兰天池高强度山线。',
    seasonGuide: '春秋最舒适。夏季午后少户外、备防晒与补液；冬湿冷缩短江边停留。',
    whyFast: '黄鹤楼可半日外观；主体留给东湖与省博休整。',
    notices: [
      '黄鹤楼票务与限流以景区当日为准；台阶多可量力外观。',
      '东湖绿道防滑、防晒；暑热改室内。',
      '夏湿热；高血压注意补水与作息。',
      '不与武当、三峡同趟连轴赶。',
    ],
    researchKeywords: [
      '武汉 东湖 绿道 父母',
      '黄鹤楼 攻略 台阶',
      '湖北省博物馆 预约',
    ],
    sources: [
      {
        title: 'Wikivoyage：武汉',
        url: 'https://zh.wikivoyage.org/wiki/%E6%AD%A6%E6%B1%89',
        kind: 'other',
        note: '城区与东湖概览，已改写',
      },
      {
        title: '湖北省博物馆',
        url: 'https://www.hbww.org/',
        kind: 'official',
        note: '预约与开放以官网为准',
      },
    ],
    stops: [
      {
        id: 'wh-wuchang-base',
        name: '武昌/洪山慢住',
        days: 2,
        pace: 'slow',
        lat: 30.55,
        lng: 114.35,
        summary: '近东湖或街道口电梯酒店；抵达日只散步歇脚。',
        tips: '高铁出站打车；备薄外套。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Wuhan_from_Yellow_Crane_Tower.jpg/1280px-Wuhan_from_Yellow_Crane_Tower.jpg',
      },
      {
        id: 'wh-yellow-crane',
        name: '黄鹤楼（量力）',
        days: 1,
        pace: 'slow',
        lat: 30.544,
        lng: 114.302,
        summary: '园区平路+远观长江；登楼台阶量大可整段外观。',
        tips: '人多即撤；暑热缩短。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Yellow_Crane_Tower_61469-Wuhan_%2849149984218%29.jpg/1280px-Yellow_Crane_Tower_61469-Wuhan_%2849149984218%29.jpg',
      },
      {
        id: 'wh-east-lake',
        name: '东湖绿道浅段',
        days: 1,
        pace: 'slow',
        lat: 30.55,
        lng: 114.41,
        summary: '电瓶车/观光车走平缓岸线；勿硬骑几十公里。',
        tips: '防晒防滑；腿脚紧半日足够。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Snake_Hill_in_Wuhan_%28Hubei%2C_China%29%2C_seen_from_the_west.jpg/1280px-Snake_Hill_in_Wuhan_%28Hubei%2C_China%29%2C_seen_from_the_west.jpg',
      },
      {
        id: 'wh-hubei-museum',
        name: '湖北省博物馆（可选）',
        days: 1,
        pace: 'fast',
        lat: 30.561,
        lng: 114.365,
        summary: '室内看编钟等专题，半日吹空调。',
        tips: '预约以馆方为准；周一常闭。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Wuhan_from_Yellow_Crane_Tower.jpg/1280px-Wuhan_from_Yellow_Crane_Tower.jpg',
      },
      {
        id: 'wh-jianghan-optional',
        name: '江汉路/汉口江滩（可选）',
        days: 1,
        pace: 'fast',
        lat: 30.584,
        lng: 114.289,
        summary: '平地步行街与江滩浅逛；可整段删。',
        tips: '暑热改晚上短走。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Wuhan_from_Yellow_Crane_Tower.jpg/1280px-Wuhan_from_Yellow_Crane_Tower.jpg',
      },
    ],
  },
  {
    id: 'huazhong-hunan-changsha',
    title: '长沙 · 岳麓橘子洲与县域浅走',
    region: 'huazhong',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约4–6天',
    transport: '北京西/丰台高铁至长沙南约5–6小时，或飞黄花；市内地铁/打车；宁乡花明楼包车日归可选。结束后高铁或飞回北京',
    budgetLabel: '本趟约2500–4500元（高铁/机票+电梯酒店；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Yuelu_Academy.jpg/1280px-Yuelu_Academy.jpg',
    summary: '把长沙织成「湘江锚点+县域可选」：岳麓书院平缓段、橘子洲江风、省博空调日；坡子街浅尝微辣。宁乡花明楼可选日归。夏湿热改早晚与室内。',
    introduction: '长沙市辖岳麓/芙蓉/天心等区与宁乡等县。爸妈优先五一广场或湘江边电梯酒店，书院与洲上分日，勿岳麓山硬爬全顶。\n\n花明楼车程可控可删。不排韶山特种兵连轴（除非体健另日）。',
    seasonGuide: '春秋最佳。夏季午后少久站；冬湿冷备厚外套。本线含夏季以便 Explore 当季可见，须严格避暑策略。',
    whyFast: '花明楼、老街夜市均可删；主体书院+橘子洲+省博。',
    notices: [
      '岳麓山登顶可整段跳过；书院为主。',
      '省博提前预约；周一常闭。',
      '湘菜点微辣/免辣。',
      '宁乡花明楼可删；勿与张家界同趟硬赶。',
    ],
    researchKeywords: [
      '长沙 岳麓书院 父母',
      '橘子洲 省博 三日',
      '宁乡 花明楼 日归',
    ],
    sources: [
      {
        title: 'Wikivoyage：长沙',
        url: 'https://zh.wikivoyage.org/wiki/%E9%95%BF%E6%B2%99',
        kind: 'other',
        note: '城区概览，已改写',
      },
      {
        title: '湖南省博物馆',
        url: 'https://www.hnmuseum.com/',
        kind: 'official',
        note: '预约以官网为准',
      },
      {
        title: '长沙市文化和旅游局',
        url: 'http://wlj.changsha.gov.cn/',
        kind: 'official',
        note: '文旅提示参考',
      },
    ],
    stops: [
      {
        id: 'cs-xiangjiang-base',
        name: '湘江边/五一慢住',
        days: 2,
        pace: 'slow',
        lat: 28.195,
        lng: 112.977,
        summary: '电梯酒店连住；抵达日沿江短走熟悉超市医院。',
        tips: '长沙南打车约30–40分钟。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Orange_Isle.jpg/1280px-Orange_Isle.jpg',
      },
      {
        id: 'yuelu-academy',
        name: '岳麓书院 · 山脚段',
        days: 1,
        pace: 'slow',
        lat: 28.184,
        lng: 112.935,
        summary: '书院庭院平缓；山路登顶量力跳过。',
        tips: '早到人少；石阶防滑。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Yuelu_Academy.jpg/1280px-Yuelu_Academy.jpg',
      },
      {
        id: 'orange-isle-oldstreet',
        name: '橘子洲 · 老街浅逛',
        days: 1,
        pace: 'slow',
        lat: 28.185,
        lng: 112.96,
        summary: '江心洲平路吹风；傍晚太平/坡子街浅逛。',
        tips: '洲上风大备外套；辣食量力。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Orange_Isle.jpg/1280px-Orange_Isle.jpg',
      },
      {
        id: 'hunan-museum',
        name: '湖南省博物馆（可选）',
        days: 1,
        pace: 'fast',
        lat: 28.214,
        lng: 112.99,
        summary: '室内专题半日；与登山日错开。',
        tips: '提前预约。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Hunan_Provincial_Museum.jpg/1280px-Hunan_Provincial_Museum.jpg',
      },
      {
        id: 'cs-ningxiang-optional',
        name: '宁乡花明楼（可选）',
        days: 1,
        pace: 'fast',
        lat: 28.12,
        lng: 112.55,
        summary: '包车日归纪念馆平缓参观；可整段删。',
        tips: '勿与市区景点同日特种兵。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Yuelu_Academy.jpg/1280px-Yuelu_Academy.jpg',
      },
    ],
  },
  {
    id: 'huazhong-henan-zhengzhou',
    title: '郑州 · 黄河与少林浅访',
    region: 'huazhong',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: true,
    daysLabel: '约3–5天',
    transport: '北京西高铁至郑州东约2.5–3.5小时；市区地铁/打车；登封少林包车或旅游巴士日归。结束后高铁回京',
    budgetLabel: '本趟约1800–3600元（高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Shaolin_Monastery.jpg/1280px-Shaolin_Monastery.jpg',
    summary: '河南枢纽补线：郑州东慢住，黄河风景名胜区观光车浅览，登封少林量力日归（景区大巴减步）。不排嵩山硬爬。可与洛阳开封线衔接但不强求同趟。',
    introduction: '郑州市辖金水/二七等区与登封市。爸妈以市区电梯酒店为锚，黄河与少林分日；少林商业化步行距离长，预留休息。\n\n洛阳龙门见独立线，本线不硬塞。',
    seasonGuide: '春秋舒适。夏季中原炎热改早晚；雾霾日改室内。',
    whyFast: '少林可删；主体黄河+休整，或直接转洛阳线。',
    notices: [
      '少林景区大、步行多，量力半日。',
      '黄河区观光车优先。',
      '暑热补水；勿嵩山连爬。',
    ],
    researchKeywords: [
      '郑州 黄河 风景区 父母',
      '少林寺 日归 攻略',
      '郑州东 高铁 三日',
    ],
    sources: [
      {
        title: 'Wikivoyage：郑州',
        url: 'https://zh.wikivoyage.org/wiki/%E9%83%91%E5%B7%9E',
        kind: 'other',
        note: '枢纽与周边概览，已改写',
      },
      {
        title: 'Wikivoyage：登封',
        url: 'https://zh.wikivoyage.org/wiki/%E7%99%BB%E5%B0%81',
        kind: 'other',
        note: '少林进出参考',
      },
    ],
    stops: [
      {
        id: 'zz-jinshui-base',
        name: '金水/郑东慢住',
        days: 2,
        pace: 'slow',
        lat: 34.78,
        lng: 113.72,
        summary: '近郑州东或地铁电梯酒店；抵达日休整。',
        tips: '出站即酒店最省力。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/27427-Luoyang_%2849067744628%29.jpg/1280px-27427-Luoyang_%2849067744628%29.jpg',
      },
      {
        id: 'zz-yellow-river',
        name: '黄河风景名胜区',
        days: 1,
        pace: 'slow',
        lat: 34.95,
        lng: 113.5,
        summary: '观光车看黄河风貌；少步行陡坡。',
        tips: '风大备外套；半日足够。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/27427-Luoyang_%2849067744628%29.jpg/1280px-27427-Luoyang_%2849067744628%29.jpg',
      },
      {
        id: 'zz-shaolin-optional',
        name: '登封少林（可选）',
        days: 1,
        pace: 'fast',
        lat: 34.51,
        lng: 112.94,
        summary: '景区交通进出；少林寺核心区浅访，不练武体验硬排。',
        tips: '可整段删；腿脚紧优先删。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Shaolin_Monastery.jpg/1280px-Shaolin_Monastery.jpg',
      },
      {
        id: 'zz-henan-museum-optional',
        name: '河南博物院（可选）',
        days: 1,
        pace: 'fast',
        lat: 34.79,
        lng: 113.67,
        summary: '市区空调馆；选一段专题即可。',
        tips: '预约以馆方为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Iron_Pagoda.jpg/1280px-Iron_Pagoda.jpg',
      },
    ],
  },
  {
    id: 'huadong-anhui-hefei',
    title: '合肥 · 巢湖与三河古镇',
    region: 'huadong',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京南高铁至合肥南约4–4.5小时；市区地铁/打车；三河古镇包车或公交日归。结束后高铁回京或转黄山线',
    budgetLabel: '本趟约1800–3500元（高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tunxi_Old_Street.jpg/1280px-Tunxi_Old_Street.jpg',
    summary: '安徽省会补线：天鹅湖/包公园平地散步，三河古镇水乡浅逛；不排大蜀山硬爬。可作黄山徽州线的前后缓冲。',
    introduction: '合肥市辖包河/蜀山等区与巢湖、肥西等。爸妈优先政务区或地铁沿线电梯酒店；三河石板防滑、半日足够。',
    seasonGuide: '春秋舒适。夏季午休；梅雨湿滑防滑鞋。',
    whyFast: '三河可删；主体市区湖公园休整。',
    notices: [
      '三河石板路防滑。',
      '暑热改室内博物馆。',
      '勿与黄山主峰同日连轴。',
    ],
    researchKeywords: [
      '合肥 三河古镇 父母',
      '合肥 天鹅湖 慢走',
      '合肥南 高铁',
    ],
    sources: [
      {
        title: 'Wikivoyage：合肥',
        url: 'https://zh.wikivoyage.org/wiki/%E5%90%88%E8%82%A5',
        kind: 'other',
        note: '城区与三河概览，已改写',
      },
    ],
    stops: [
      {
        id: 'hf-baohe-base',
        name: '包河/政务区慢住',
        days: 2,
        pace: 'slow',
        lat: 31.82,
        lng: 117.28,
        summary: '电梯酒店；抵达日湖边短走。',
        tips: '合肥南出站打车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tunxi_Old_Street.jpg/1280px-Tunxi_Old_Street.jpg',
      },
      {
        id: 'hf-swan-lake',
        name: '天鹅湖/包公园',
        days: 1,
        pace: 'slow',
        lat: 31.82,
        lng: 117.27,
        summary: '平路环湖或公园散步；半日。',
        tips: '暑热早晚去。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tunxi_Old_Street.jpg/1280px-Tunxi_Old_Street.jpg',
      },
      {
        id: 'hf-sanhe-optional',
        name: '三河古镇（可选）',
        days: 1,
        pace: 'fast',
        lat: 31.52,
        lng: 117.28,
        summary: '水乡街巷浅逛；石板防滑，可删。',
        tips: '日归不换店。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Huangshan_pic_4.jpg/1280px-Huangshan_pic_4.jpg',
      },
      {
        id: 'hf-anhui-museum-optional',
        name: '安徽博物院（可选）',
        days: 1,
        pace: 'fast',
        lat: 31.84,
        lng: 117.25,
        summary: '室内专题；空调日。',
        tips: '预约以馆方为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tunxi_Old_Street.jpg/1280px-Tunxi_Old_Street.jpg',
      },
    ],
  },
  {
    id: 'huanan-fujian-fuzhou',
    title: '福州 · 三坊七巷慢走',
    region: 'huanan',
    seasons: ["spring", "autumn", "winter", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京飞长乐机场，或高铁经浦城/南平至福州；市区地铁/打车。结束后飞回北京或南下厦门/泉州',
    budgetLabel: '本趟约2200–4000元（机票/高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Kaiyuan_Temple_%28Quanzhou%29.jpg/1280px-Kaiyuan_Temple_%28Quanzhou%29.jpg',
    summary: '福建省会补线：三坊七巷街区平缓观光，西湖公园散步；暑湿热改早晚。可与厦门泉州串，但本线独立可回京。',
    introduction: '福州市辖鼓楼/台江等区。爸妈住三坊七巷附近电梯酒店，坊巷分两日浅走，勿一日塞满爬山。',
    seasonGuide: '冬春舒适；夏湿热台风季关注预警；秋亦可。',
    whyFast: '西湖公园可删；主体三坊七巷。',
    notices: [
      '暑湿热；台风天改室内。',
      '坊巷石板防滑。',
      '勿与武夷山硬爬同趟。',
    ],
    researchKeywords: [
      '福州 三坊七巷 攻略 父母',
      '福州 西湖公园',
      '福州 高铁 三日',
    ],
    sources: [
      {
        title: 'Wikivoyage：福州',
        url: 'https://zh.wikivoyage.org/wiki/%E7%A6%8F%E5%B7%9E',
        kind: 'other',
        note: '城区概览，已改写',
      },
    ],
    stops: [
      {
        id: 'fz-gulou-base',
        name: '鼓楼慢住',
        days: 2,
        pace: 'slow',
        lat: 26.08,
        lng: 119.3,
        summary: '近三坊七巷电梯酒店。',
        tips: '机场大巴或打车入城。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Kaiyuan_Temple_%28Quanzhou%29.jpg/1280px-Kaiyuan_Temple_%28Quanzhou%29.jpg',
      },
      {
        id: 'fz-sanfang',
        name: '三坊七巷',
        days: 1,
        pace: 'slow',
        lat: 26.083,
        lng: 119.293,
        summary: '街区平缓；分上下午或两日。',
        tips: '人多即撤侧巷。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Xiamen.jpg/1280px-Xiamen.jpg',
      },
      {
        id: 'fz-west-lake-optional',
        name: '福州西湖公园（可选）',
        days: 1,
        pace: 'fast',
        lat: 26.09,
        lng: 119.29,
        summary: '平路环湖；可删。',
        tips: '暑热早晚。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Xiamen.jpg/1280px-Xiamen.jpg',
      },
      {
        id: 'fz-rongcheng-optional',
        name: '上下杭/中洲岛浅逛（可选）',
        days: 1,
        pace: 'fast',
        lat: 26.05,
        lng: 119.31,
        summary: '沿河平地；可删。',
        tips: '防滑。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Kaiyuan_Temple_%28Quanzhou%29.jpg/1280px-Kaiyuan_Temple_%28Quanzhou%29.jpg',
      },
    ],
  },
  {
    id: 'huadong-jiangxi-nanchang',
    title: '南昌 · 滕王阁与秋水广场',
    region: 'huadong',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京西高铁至南昌西约5–6小时，或飞昌北；市区地铁/打车。结束后高铁回京或转婺源',
    budgetLabel: '本趟约2000–3800元（高铁/机票+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Wuyuan_Jiangxi.jpg/1280px-Wuyuan_Jiangxi.jpg',
    summary: '江西省会补线：滕王阁量力外观或浅登，秋水广场赣江边平走，八一纪念馆室内可选。暑热改室内。可作婺源线前后缓冲。',
    introduction: '南昌市辖东湖/红谷滩等。爸妈优先红谷滩或地铁沿线电梯酒店；滕王阁台阶量力。',
    seasonGuide: '春秋舒适。夏季酷热严格午休。',
    whyFast: '纪念馆可删；主体江边+滕王阁外观。',
    notices: [
      '滕王阁台阶量力外观。',
      '暑热补水。',
      '勿与婺源花期人潮同日硬赶。',
    ],
    researchKeywords: [
      '南昌 滕王阁 父母',
      '秋水广场 南昌',
      '南昌西 高铁',
    ],
    sources: [
      {
        title: 'Wikivoyage：南昌',
        url: 'https://zh.wikivoyage.org/wiki/%E5%8D%97%E6%98%8C',
        kind: 'other',
        note: '城区概览，已改写',
      },
    ],
    stops: [
      {
        id: 'nc-honggutan-base',
        name: '红谷滩/东湖慢住',
        days: 2,
        pace: 'slow',
        lat: 28.69,
        lng: 115.86,
        summary: '电梯酒店；抵达日江边短走。',
        tips: '南昌西打车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Wuyuan_Jiangxi.jpg/1280px-Wuyuan_Jiangxi.jpg',
      },
      {
        id: 'nc-tengwang',
        name: '滕王阁（量力）',
        days: 1,
        pace: 'slow',
        lat: 28.683,
        lng: 115.875,
        summary: '外观或浅登；台阶多可园区平地。',
        tips: '预约以景区为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Wuyuan_Jiangxi.jpg/1280px-Wuyuan_Jiangxi.jpg',
      },
      {
        id: 'nc-qiushui',
        name: '秋水广场 · 赣江边',
        days: 1,
        pace: 'slow',
        lat: 28.69,
        lng: 115.85,
        summary: '平路观江；半日。',
        tips: '风大备外套。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Wuyuan_Jiangxi.jpg/1280px-Wuyuan_Jiangxi.jpg',
      },
      {
        id: 'nc-bayi-optional',
        name: '八一起义纪念馆（可选）',
        days: 1,
        pace: 'fast',
        lat: 28.68,
        lng: 115.9,
        summary: '室内看展；可删。',
        tips: '预约以馆方为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Wuyuan_Jiangxi.jpg/1280px-Wuyuan_Jiangxi.jpg',
      },
    ],
  },
  {
    id: 'huabei-shanxi-taiyuan',
    title: '太原 · 晋祠与省博慢游',
    region: 'huabei',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: true,
    daysLabel: '约3–5天',
    transport: '北京西/丰台高铁至太原南约2.5–3小时；市区地铁/打车；晋祠公交或打车。结束后高铁回京或转平遥',
    budgetLabel: '本趟约1600–3200元（高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Taiyuan_Shanxi_China.jpg/1280px-Taiyuan_Shanxi_China.jpg',
    summary: '山西太原独立线：晋祠园林平缓段、山西省博物院空调日、汾河公园散步。与平遥深度线互补；本线可不去平遥。',
    introduction: '太原市辖迎泽/小店等。爸妈近地铁电梯酒店；晋祠与省博分日。面食选清汤。',
    seasonGuide: '春秋舒适。夏季干热；冬寒雾霾可缩短。',
    whyFast: '汾河可删；主体晋祠+省博。',
    notices: [
      '晋祠石径防滑。',
      '省博预约。',
      '面食少油腻。',
    ],
    researchKeywords: [
      '太原 晋祠 父母',
      '山西省博物院',
      '太原南 高铁 三日',
    ],
    sources: [
      {
        title: 'Wikivoyage：太原',
        url: 'https://zh.wikivoyage.org/wiki/%E5%A4%AA%E5%8E%9F',
        kind: 'other',
        note: '城区与晋祠概览，已改写',
      },
    ],
    stops: [
      {
        id: 'ty-yingze-base',
        name: '迎泽/小店慢住',
        days: 2,
        pace: 'slow',
        lat: 37.87,
        lng: 112.55,
        summary: '近太原南或地铁电梯酒店。',
        tips: '出站休整。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Taiyuan_Shanxi_China.jpg/1280px-Taiyuan_Shanxi_China.jpg',
      },
      {
        id: 'ty-jinci',
        name: '晋祠',
        days: 1,
        pace: 'slow',
        lat: 37.71,
        lng: 112.43,
        summary: '园林与古建平缓段；半日至一日。',
        tips: '石径防滑。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Pingyao_40.JPG/1280px-Pingyao_40.JPG',
      },
      {
        id: 'ty-shanxi-museum',
        name: '山西省博物院',
        days: 1,
        pace: 'slow',
        lat: 37.86,
        lng: 112.53,
        summary: '室内专题；空调日。',
        tips: '预约以馆方为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Taiyuan_Shanxi_China.jpg/1280px-Taiyuan_Shanxi_China.jpg',
      },
      {
        id: 'ty-fenhe-optional',
        name: '汾河公园（可选）',
        days: 1,
        pace: 'fast',
        lat: 37.87,
        lng: 112.54,
        summary: '平路散步；可删。',
        tips: '风大备外套。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Taiyuan_Shanxi_China.jpg/1280px-Taiyuan_Shanxi_China.jpg',
      },
    ],
  },
  {
    id: 'huanan-guangdong-shenzhen',
    title: '深圳 · 湾区海岸浅游',
    region: 'huanan',
    seasons: ["autumn", "winter", "spring"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京飞宝安机场，或高铁经广州至深圳北/福田；市内地铁。结束后飞回北京',
    budgetLabel: '本趟约2500–4500元（机票/高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg/1280px-Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg',
    summary: '一线补线：深圳湾/海边栈道平走，华侨城或博物馆室内可选；不排高强度登山。冬春舒适，暑湿热缩短户外。',
    introduction: '深圳市辖南山区等。爸妈优先南山或地铁沿线电梯酒店；海岸线与室内展分日。',
    seasonGuide: '秋冬春舒适。夏季湿热暴雨，缩短户外。',
    whyFast: '主题公园可删；主体湾区散步+一处室内。',
    notices: [
      '海边防晒防滑。',
      '地铁高峰少挤。',
      '勿一日多区特种兵。',
    ],
    researchKeywords: [
      '深圳湾 公园 父母',
      '深圳 海岸 慢走',
      '深圳 博物馆',
    ],
    sources: [
      {
        title: 'Wikivoyage：深圳',
        url: 'https://zh.wikivoyage.org/wiki/%E6%B7%B1%E5%9C%B3',
        kind: 'other',
        note: '城区与海岸概览，已改写',
      },
    ],
    stops: [
      {
        id: 'sz-nanshan-base',
        name: '南山慢住',
        days: 2,
        pace: 'slow',
        lat: 22.53,
        lng: 113.93,
        summary: '电梯酒店；抵达日休整。',
        tips: '机场地铁或打车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg/1280px-Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg',
      },
      {
        id: 'sz-shenzhen-bay',
        name: '深圳湾公园栈道',
        days: 1,
        pace: 'slow',
        lat: 22.52,
        lng: 113.99,
        summary: '平路看海；半日。',
        tips: '防晒；暑热早晚。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg/1280px-Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg',
      },
      {
        id: 'sz-oct-optional',
        name: '华侨城/室内展（可选）',
        days: 1,
        pace: 'fast',
        lat: 22.54,
        lng: 113.98,
        summary: '室内或平缓园区择一；可删。',
        tips: '人多即撤。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Canton_Tower_20241027.jpg/1280px-Canton_Tower_20241027.jpg',
      },
      {
        id: 'sz-dameisha-optional',
        name: '大梅沙外观（可选）',
        days: 1,
        pace: 'fast',
        lat: 22.59,
        lng: 114.31,
        summary: '滨海短停；可删。',
        tips: '风浪大改湾区。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg/1280px-Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg',
      },
    ],
  },
  {
    id: 'huabei-shandong-jinan',
    title: '济南 · 泉城与大明湖',
    region: 'huabei',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: true,
    daysLabel: '约2–4天',
    transport: '北京南高铁至济南西约1.5–2小时；市内打车/公交。结束后高铁回京或转青岛/泰山',
    budgetLabel: '本趟约1200–2600元（高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Jinan_Baotu_Spring-20150519-RM-165055.jpg/1280px-Jinan_Baotu_Spring-20150519-RM-165055.jpg',
    summary: '山东省会补线：趵突泉与大明湖平缓游览，泉城路浅逛。可作青岛/泰山线的缓冲，不必同趟排满。',
    introduction: '济南市辖历下等区。爸妈住泉城广场附近电梯酒店；泉水景区石板防滑。',
    seasonGuide: '春秋舒适。夏季闷热；泉水四季可看。',
    whyFast: '泉城路可删；主体趵突泉+大明湖。',
    notices: [
      '景区石板防滑。',
      '暑热午休。',
      '勿与泰山硬爬同日。',
    ],
    researchKeywords: [
      '济南 趵突泉 父母',
      '大明湖 慢走',
      '济南西 高铁',
    ],
    sources: [
      {
        title: 'Wikivoyage：济南',
        url: 'https://zh.wikivoyage.org/wiki/%E6%B5%8E%E5%8D%97',
        kind: 'other',
        note: '泉城概览，已改写',
      },
    ],
    stops: [
      {
        id: 'jn-lishi-base',
        name: '历下慢住',
        days: 1,
        pace: 'slow',
        lat: 36.66,
        lng: 117.02,
        summary: '近泉城广场电梯酒店。',
        tips: '济南西打车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Jinan_Baotu_Spring-20150519-RM-165055.jpg/1280px-Jinan_Baotu_Spring-20150519-RM-165055.jpg',
      },
      {
        id: 'jn-baotu',
        name: '趵突泉',
        days: 1,
        pace: 'slow',
        lat: 36.66,
        lng: 117.01,
        summary: '园区平缓看泉；半日。',
        tips: '石板防滑。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Jinan_Baotu_Spring-20150519-RM-165055.jpg/1280px-Jinan_Baotu_Spring-20150519-RM-165055.jpg',
      },
      {
        id: 'jn-daming',
        name: '大明湖',
        days: 1,
        pace: 'slow',
        lat: 36.67,
        lng: 117.03,
        summary: '环湖平路或坐船减步。',
        tips: '暑热早晚。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Jinan_Baotu_Spring-20150519-RM-165055.jpg/1280px-Jinan_Baotu_Spring-20150519-RM-165055.jpg',
      },
      {
        id: 'jn-quancheng-optional',
        name: '泉城路浅逛（可选）',
        days: 1,
        pace: 'fast',
        lat: 36.66,
        lng: 117.02,
        summary: '平地商业街；可删。',
        tips: '人多即撤。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Jinan_Baotu_Spring-20150519-RM-165055.jpg/1280px-Jinan_Baotu_Spring-20150519-RM-165055.jpg',
      },
    ],
  },
  {
    id: 'dongbei-jilin-changchun',
    title: '长春 · 伪满与南湖浅走',
    region: 'dongbei',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京高铁至长春约5–6小时，或飞龙嘉；市内打车/公交。结束后高铁回京或转长白山/延边',
    budgetLabel: '本趟约2000–3800元（高铁/机票+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Yanji.jpg/1280px-Yanji.jpg',
    summary: '吉林省会补线：伪满皇宫博物院室内看展，南湖公园平路散步。冬寒另议；本线偏春秋夏。可作长白山前后缓冲。',
    introduction: '长春市辖南关/朝阳等。爸妈近公园或地铁电梯酒店；伪满馆室内为主。',
    seasonGuide: '春秋舒适。夏季蚊虫；冬极寒不排本线主体。',
    whyFast: '南湖可删；主体伪满室内。',
    notices: [
      '伪满馆预约。',
      '南湖防滑。',
      '勿与长白山同日连轴。',
    ],
    researchKeywords: [
      '长春 伪满皇宫 父母',
      '南湖公园 长春',
      '长春 高铁 三日',
    ],
    sources: [
      {
        title: 'Wikivoyage：长春',
        url: 'https://zh.wikivoyage.org/wiki/%E9%95%BF%E6%98%A5',
        kind: 'other',
        note: '城区概览，已改写',
      },
    ],
    stops: [
      {
        id: 'cc-chaoyang-base',
        name: '朝阳/南关慢住',
        days: 2,
        pace: 'slow',
        lat: 43.88,
        lng: 125.32,
        summary: '电梯酒店；抵达休整。',
        tips: '高铁站打车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Yanji.jpg/1280px-Yanji.jpg',
      },
      {
        id: 'cc-puppet-palace',
        name: '伪满皇宫博物院',
        days: 1,
        pace: 'slow',
        lat: 43.91,
        lng: 125.35,
        summary: '室内展陈为主；半日到一日。',
        tips: '预约以馆方为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Yanji.jpg/1280px-Yanji.jpg',
      },
      {
        id: 'cc-nanhu',
        name: '南湖公园',
        days: 1,
        pace: 'slow',
        lat: 43.85,
        lng: 125.31,
        summary: '平路环湖；半日。',
        tips: '风大备外套。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/%E4%BB%8E%E9%95%BF%E7%99%BD%E5%B1%B1%E8%A5%BF%E5%9D%A1%E7%9C%8B%E5%A4%A9%E6%B1%A0-2017-08-24_1.jpg/1280px-%E4%BB%8E%E9%95%BF%E7%99%BD%E5%B1%B1%E8%A5%BF%E5%9D%A1%E7%9C%8B%E5%A4%A9%E6%B1%A0-2017-08-24_1.jpg',
      },
      {
        id: 'cc-cultural-optional',
        name: '文化广场浅逛（可选）',
        days: 1,
        pace: 'fast',
        lat: 43.86,
        lng: 125.32,
        summary: '平地短走；可删。',
        tips: '人多即撤。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Yanji.jpg/1280px-Yanji.jpg',
      },
    ],
  },
  {
    id: 'huadong-jiangsu-nanjing',
    title: '南京 · 博物院与玄武湖',
    region: 'huadong',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京南高铁至南京南约3.5–4.5小时；市内地铁。结束后高铁回京或转苏州扬州',
    budgetLabel: '本趟约2000–3800元（高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Nanjing_Museum.jpg/1280px-Nanjing_Museum.jpg',
    summary: '江苏南京独立线：南京博物院空调看展，玄武湖平路或游船，老城南浅逛可选。中山陵台阶多默认量力或外观。',
    introduction: '南京市辖玄武/秦淮等。爸妈近地铁电梯酒店；博物院与玄武湖分日。中山陵不强制。',
    seasonGuide: '春秋最佳。夏季闷热改室内；冬湿冷备厚外套。',
    whyFast: '中山陵/夫子庙可删；主体南博+玄武湖。',
    notices: [
      '南博预约闭馆日。',
      '中山陵台阶量大可删。',
      '暑热午休。',
    ],
    researchKeywords: [
      '南京博物院 父母',
      '玄武湖 游船',
      '南京南 高铁 三日',
    ],
    sources: [
      {
        title: 'Wikivoyage：南京',
        url: 'https://zh.wikivoyage.org/wiki/%E5%8D%97%E4%BA%AC',
        kind: 'other',
        note: '城区概览，已改写',
      },
      {
        title: '南京博物院',
        url: 'https://www.njmuseum.com/',
        kind: 'official',
        note: '预约以官网为准',
      },
    ],
    stops: [
      {
        id: 'nj-xuanwu-base',
        name: '玄武/秦淮慢住',
        days: 2,
        pace: 'slow',
        lat: 32.06,
        lng: 118.79,
        summary: '近地铁电梯酒店。',
        tips: '南京南地铁入城。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Nanjing_Museum.jpg/1280px-Nanjing_Museum.jpg',
      },
      {
        id: 'nj-museum',
        name: '南京博物院',
        days: 1,
        pace: 'slow',
        lat: 32.04,
        lng: 118.83,
        summary: '室内专题；半日到一日。',
        tips: '周一常闭；预约。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Nanjing_Museum.jpg/1280px-Nanjing_Museum.jpg',
      },
      {
        id: 'nj-xuanwu-lake',
        name: '玄武湖',
        days: 1,
        pace: 'slow',
        lat: 32.07,
        lng: 118.79,
        summary: '环湖平路或游船减步。',
        tips: '暑热早晚。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Humble_Administrator%27s_Garden_2015.JPG/1280px-Humble_Administrator%27s_Garden_2015.JPG',
      },
      {
        id: 'nj-zijin-optional',
        name: '中山陵外观（可选）',
        days: 1,
        pace: 'fast',
        lat: 32.07,
        lng: 118.85,
        summary: '台阶多，默认外观或短段；可删。',
        tips: '腿脚紧必删。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Nanjing_Museum.jpg/1280px-Nanjing_Museum.jpg',
      },
    ],
  },
  {
    id: 'xinan-guizhou-guiyang',
    title: '贵阳 · 甲秀楼与黔中慢住',
    region: 'xinan',
    seasons: ["spring", "autumn", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京飞龙洞堡，或高铁经怀化等至贵阳北；市区公交/打车。结束后飞回北京或转黄果树/镇远',
    budgetLabel: '本趟约2200–4200元（机票/高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Guiyang.jpg/1280px-Guiyang.jpg',
    summary: '贵州省会补线：甲秀楼/南明河平缓，黔灵山仅山脚或索道量力；市区慢住作黄果树镇远缓冲。夏凉是优势，雨天石板防滑。',
    introduction: '贵阳市辖南明/云岩等。爸妈住南明河附近电梯酒店；黔灵山不硬爬。',
    seasonGuide: '夏季相对凉爽；春秋亦可。雨季防滑。',
    whyFast: '黔灵山可删；主体河岸+甲秀楼。',
    notices: [
      '雨天石板防滑。',
      '黔灵山硬爬可删。',
      '酸辣适量。',
    ],
    researchKeywords: [
      '贵阳 甲秀楼 父母',
      '黔灵山 索道',
      '贵阳 慢住',
    ],
    sources: [
      {
        title: 'Wikivoyage：贵阳',
        url: 'https://zh.wikivoyage.org/wiki/%E8%B4%B5%E9%98%B3',
        kind: 'other',
        note: '城区概览，已改写',
      },
    ],
    stops: [
      {
        id: 'gy-nanming-base',
        name: '南明慢住',
        days: 2,
        pace: 'slow',
        lat: 26.57,
        lng: 106.71,
        summary: '电梯酒店；抵达适应。',
        tips: '机场大巴或打车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Guiyang.jpg/1280px-Guiyang.jpg',
      },
      {
        id: 'gy-jiaxiu',
        name: '甲秀楼 · 南明河',
        days: 1,
        pace: 'slow',
        lat: 26.57,
        lng: 106.72,
        summary: '河岸平走与楼外观；半日。',
        tips: '雨天防滑。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Guiyang.jpg/1280px-Guiyang.jpg',
      },
      {
        id: 'gy-qianling-optional',
        name: '黔灵山山脚/索道（可选）',
        days: 1,
        pace: 'fast',
        lat: 26.59,
        lng: 106.69,
        summary: '不硬爬；索道或山脚即返，可删。',
        tips: '台阶多必量力。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Huangguoshu_Waterfall.jpg/1280px-Huangguoshu_Waterfall.jpg',
      },
      {
        id: 'gy-museum-optional',
        name: '贵州省博物馆（可选）',
        days: 1,
        pace: 'fast',
        lat: 26.58,
        lng: 106.72,
        summary: '室内专题；可删。',
        tips: '预约以馆方为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Guiyang.jpg/1280px-Guiyang.jpg',
      },
    ],
  },
  {
    id: 'huanan-guangxi-nanning',
    title: '南宁 · 青秀山与邕江慢走',
    region: 'huanan',
    seasons: ["autumn", "winter", "spring"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京飞吴圩，或高铁经南宁东；市区地铁/打车。结束后飞回北京或转桂林/德天',
    budgetLabel: '本趟约2200–4000元（机票/高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nanning.jpg/1280px-Nanning.jpg',
    summary: '广西省会补线：青秀山观光车/索道减负，邕江边平走。可作德天/桂林缓冲，不必同趟排满。',
    introduction: '南宁市辖青秀等区。爸妈住青秀山附近电梯酒店；山路不硬爬。',
    seasonGuide: '秋冬春舒适。夏季湿热暴雨缩短户外。',
    whyFast: '博物馆可删；主体青秀山减负+江边。',
    notices: [
      '青秀山用观光车。',
      '暑热蚊虫。',
      '勿与德天同日连轴。',
    ],
    researchKeywords: [
      '南宁 青秀山 观光车',
      '邕江 慢走',
      '南宁 父母 三日',
    ],
    sources: [
      {
        title: 'Wikivoyage：南宁',
        url: 'https://zh.wikivoyage.org/wiki/%E5%8D%97%E5%AE%81',
        kind: 'other',
        note: '城区概览，已改写',
      },
    ],
    stops: [
      {
        id: 'nn-qingxiu-base',
        name: '青秀慢住',
        days: 2,
        pace: 'slow',
        lat: 22.82,
        lng: 108.4,
        summary: '电梯酒店；抵达休整。',
        tips: '机场大巴。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nanning.jpg/1280px-Nanning.jpg',
      },
      {
        id: 'nn-qingxiu-mountain',
        name: '青秀山（观光车）',
        days: 1,
        pace: 'slow',
        lat: 22.84,
        lng: 108.4,
        summary: '观光车/索道减负；半日。',
        tips: '勿硬爬。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nanning.jpg/1280px-Nanning.jpg',
      },
      {
        id: 'nn-yongjiang',
        name: '邕江边浅走',
        days: 1,
        pace: 'slow',
        lat: 22.81,
        lng: 108.37,
        summary: '平路江景；半日。',
        tips: '防晒。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nanning.jpg/1280px-Nanning.jpg',
      },
      {
        id: 'nn-museum-optional',
        name: '广西博物馆（可选）',
        days: 1,
        pace: 'fast',
        lat: 22.81,
        lng: 108.36,
        summary: '室内；可删。',
        tips: '预约以馆方为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Detian_Falls.jpg/1280px-Detian_Falls.jpg',
      },
    ],
  },
  {
    id: 'huanan-hainan-haikou',
    title: '海口 · 骑楼与海岸浅住',
    region: 'huanan',
    seasons: ["winter", "autumn", "spring"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约4–7天',
    transport: '北京飞美兰机场；市区打车。结束后飞回北京或转三亚/东线长居',
    budgetLabel: '本趟约2500–4800元（机票+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sanya_Bay_panorama.jpg/1280px-Sanya_Bay_panorama.jpg',
    summary: '海南省会补线：骑楼老街平地浅逛，西海岸或假日海滩散步；冬避寒友好。可作三亚/东线前后缓冲。',
    introduction: '海口市辖龙华/秀英等。爸妈住海岸或骑楼附近电梯酒店；暑湿雷雨季慎选。',
    seasonGuide: '冬春最佳避寒。夏秋湿热台风关注预警。',
    whyFast: '火山口公园可删；主体骑楼+海岸。',
    notices: [
      '台风天改室内。',
      '海边防晒。',
      '海鲜少生冷。',
    ],
    researchKeywords: [
      '海口 骑楼 父母',
      '海口 西海岸',
      '海口 避寒',
    ],
    sources: [
      {
        title: 'Wikivoyage：海口',
        url: 'https://zh.wikivoyage.org/wiki/%E6%B5%B7%E5%8F%A3',
        kind: 'other',
        note: '城区与海岸概览，已改写',
      },
    ],
    stops: [
      {
        id: 'hk-longhua-base',
        name: '龙华/海岸慢住',
        days: 2,
        pace: 'slow',
        lat: 20.03,
        lng: 110.32,
        summary: '电梯酒店；抵达适应湿热。',
        tips: '机场打车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sanya_Bay_panorama.jpg/1280px-Sanya_Bay_panorama.jpg',
      },
      {
        id: 'hk-qilou',
        name: '骑楼老街',
        days: 1,
        pace: 'slow',
        lat: 20.04,
        lng: 110.34,
        summary: '平地街区浅逛；半日。',
        tips: '防晒补水。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sanya_Bay_panorama.jpg/1280px-Sanya_Bay_panorama.jpg',
      },
      {
        id: 'hk-west-coast',
        name: '西海岸/假日海滩',
        days: 1,
        pace: 'slow',
        lat: 20.05,
        lng: 110.25,
        summary: '平路看海；半日。',
        tips: '风浪大缩短。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sanya_Bay_panorama.jpg/1280px-Sanya_Bay_panorama.jpg',
      },
      {
        id: 'hk-volcano-optional',
        name: '火山口公园外观（可选）',
        days: 1,
        pace: 'fast',
        lat: 19.93,
        lng: 110.22,
        summary: '观光车减步；可删。',
        tips: '台阶量力。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sanya_Bay_panorama.jpg/1280px-Sanya_Bay_panorama.jpg',
      },
    ],
  },
  {
    id: 'xinan-yunnan-kunming-city',
    title: '昆明 · 滇池与翠湖慢游',
    region: 'xinan',
    seasons: ["spring", "autumn", "winter", "summer"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约4–7天',
    transport: '北京飞长水；市区地铁/打车；滇池/西山观光车。结束后飞回北京或转大理',
    budgetLabel: '本趟约2500–4500元（机票+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Kunming.jpg/1280px-Kunming.jpg',
    summary: '云南昆明城市线（互补长居主题）：翠湖散步，滇池沿岸观光车，西山索道量力。四季温和；可作滇西进出枢纽。',
    introduction: '昆明市辖五华/西山等。爸妈住翠湖或地铁沿线电梯酒店；西山不硬爬。',
    seasonGuide: '四季皆可；春季飞絮过敏者注意。',
    whyFast: '石林另日或删；主体翠湖+滇池。',
    notices: [
      '西山索道减负。',
      '滇池风大备外套。',
      '紫外线强防晒。',
    ],
    researchKeywords: [
      '昆明 滇池 父母',
      '翠湖 慢走',
      '西山 索道',
    ],
    sources: [
      {
        title: 'Wikivoyage：昆明',
        url: 'https://zh.wikivoyage.org/wiki/%E6%98%86%E6%98%8E',
        kind: 'other',
        note: '城区与滇池概览，已改写',
      },
    ],
    stops: [
      {
        id: 'km-cuihu-base',
        name: '翠湖/五华慢住',
        days: 2,
        pace: 'slow',
        lat: 25.05,
        lng: 102.7,
        summary: '电梯酒店；抵达适应。',
        tips: '机场大巴或地铁。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Kunming.jpg/1280px-Kunming.jpg',
      },
      {
        id: 'km-cuihu',
        name: '翠湖公园',
        days: 1,
        pace: 'slow',
        lat: 25.05,
        lng: 102.7,
        summary: '平路环湖；半日。',
        tips: '春季飞絮注意。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Kunming.jpg/1280px-Kunming.jpg',
      },
      {
        id: 'km-dianchi',
        name: '滇池沿岸（观光车）',
        days: 1,
        pace: 'slow',
        lat: 24.95,
        lng: 102.68,
        summary: '观光车看湖；少步行。',
        tips: '风大备外套。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Kunming.jpg/1280px-Kunming.jpg',
      },
      {
        id: 'km-xishan-optional',
        name: '西山索道观景（可选）',
        days: 1,
        pace: 'fast',
        lat: 24.96,
        lng: 102.63,
        summary: '索道减负；可删硬爬。',
        tips: '恐高量力。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Kunming.jpg/1280px-Kunming.jpg',
      },
    ],
  },
  {
    id: 'qingzang-nyingchi-slow',
    title: '林芝 · 河谷低海拔慢住',
    region: 'qingzang',
    seasons: ["summer", "autumn"],
    tripType: 'short',
    compositionKind: 'leg',
    fromHome: false,
    themes: ["corridor"],
    daysLabel: '约5–8天（建议拉萨适应后或直飞林芝）',
    transport: '优先飞林芝米林（海拔低于拉萨，仍须健康评估）；或拉萨适应稳定后沿 G318/拉林高铁东行。结束后经林芝或拉萨飞回北京（常经成都）。禁止未评估直接高强度活动。',
    budgetLabel: '本趟约5000–9000元（含高原机票与供氧住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg/1280px-Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg',
    summary: '西藏相对低海拔补充：巴宜慢住，鲁朗镇区浅逛，雅鲁藏布大峡谷口感观景（不上高强度徒步）。仍有高原风险：备血氧仪与氧气咨询医生；不适立即下撤/停游。',
    introduction: '林芝市巴宜区海拔约3000米出头，整体低于拉萨与日喀则，但仍属高原。爸妈须行前体检，选供氧电梯酒店，日行程极短。\n\n鲁朗与峡谷口以车览/短停为主。色季拉等高山口可整段删。绝不衔接阿里/珠峰。',
    seasonGuide: '夏秋适宜。冬春路况与供暖需额外评估；雨季注意塌方预警。',
    whyFast: '鲁朗/峡谷均可删；只留巴宜休整也成立。',
    notices: [
      '行前必须健康评估；心脑血管等高风险者不宜。',
      '备血氧仪、医生建议下的氧气/药物；出现持续头痛呕吐胸闷立即就医下撤。',
      '色季拉等高海拔山口可删；不安排徒步进峡谷深处。',
      '证件与进藏规定以官方为准。',
    ],
    researchKeywords: [
      '林芝 海拔 父母 高反',
      '鲁朗 林芝 慢住',
      '雅鲁藏布大峡谷 观光车',
    ],
    sources: [
      {
        title: 'Wikivoyage：林芝',
        url: 'https://zh.wikivoyage.org/wiki/%E6%9E%97%E8%8A%9D',
        kind: 'other',
        note: '海拔与进出概览，已改写',
      },
      {
        title: '西藏文旅厅',
        url: 'https://wlt.xizang.gov.cn/',
        kind: 'official',
        note: '进藏与景区公告以官方为准',
      },
    ],
    stops: [
      {
        id: 'lz-bayi-base',
        name: '巴宜慢住（适应）',
        days: 3,
        pace: 'slow',
        lat: 29.65,
        lng: 94.36,
        summary: '供氧电梯酒店连住；前两日少活动。',
        tips: '近医院；血氧自测。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg/1280px-Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg',
      },
      {
        id: 'lz-lulang',
        name: '鲁朗镇区浅逛',
        days: 1,
        pace: 'slow',
        lat: 29.76,
        lng: 94.73,
        summary: '镇区平地短走；车览为主。',
        tips: '山口不适即返巴宜。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg/1280px-Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg',
      },
      {
        id: 'lz-yarlung-optional',
        name: '雅鲁藏布大峡谷口感（可选）',
        days: 1,
        pace: 'fast',
        lat: 29.6,
        lng: 94.9,
        summary: '观景台/观光车短停；不上长线徒步，可删。',
        tips: '防滑防晒；高反加重即撤。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg/1280px-Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg',
      },
      {
        id: 'lz-buffer-optional',
        name: '空白休整日（可选）',
        days: 1,
        pace: 'fast',
        lat: 29.65,
        lng: 94.36,
        summary: '只散步超市；巩固适应。',
        tips: '可多留。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg/1280px-Shergyla_Mountain%2C_Nyingchi%2C_Tibet_Banner.jpg',
      },
    ],
  },
  // qingzang-g318-lhasa-nyingchi 已迁至 compose-qingzang-lhasa-nyingchi
  // （reuse qingzang-lhasa-slow + qingzang-nyingchi-slow；见 routes-compose-qingzang-20260802）

  {
    id: 'xinan-sichuan-g318-east',
    title: '川藏东段 · 康定新都桥浅尝',
    region: 'xinan',
    seasons: ["summer", "autumn"],
    tripType: 'short',
    fromHome: false,
    themes: ["corridor"],
    daysLabel: '约5–8天（成都平原缓冲后）',
    transport: '北京飞成都适应2–3日→飞康定或包车西行短段→新都桥观景浅停→必须下撤成都再飞北京。海拔跳变大：不适立刻下撤。不贯通至拉萨。',
    budgetLabel: '本趟约4500–8000元（含机票包车；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Xinduqiao.jpg/1280px-Xinduqiao.jpg',
    summary: 'G318 东段适老浅尝：只到康定/新都桥观景量级，不冲折多山、不进藏北。高原反应风险明确写入；可整段取消改成都平原。',
    introduction: '与川西慢线重叠风险：本线强调「走廊主题浅尝+可跳过」，日驾短。心脑血管等基础病应放弃或只留成都。',
    seasonGuide: '夏秋。雨季塌方泥石流高发路段勿硬开。',
    whyFast: '新都桥可删；只康定浅停或直接回成都。',
    notices: [
      '成都平原先适应再西行。',
      '新都桥约3300米：短停观景，不过夜或仅一晚评估。',
      '持续高反应立即下撤成都。',
      '不与林芝/拉萨段强行自驾贯通。',
    ],
    researchKeywords: [
      '新都桥 海拔 父母',
      '康定 浅游 高反',
      '川藏线 东段 适老',
    ],
    sources: [
      {
        title: 'Wikivoyage：康定',
        url: 'https://zh.wikivoyage.org/wiki/%E5%BA%B7%E5%AE%9A',
        kind: 'other',
        note: '进出与海拔提示，已改写',
      },
    ],
    stops: [
      {
        id: 'g318e-chengdu-buffer',
        name: '成都平原缓冲',
        days: 3,
        pace: 'slow',
        lat: 30.67,
        lng: 104.06,
        summary: '先休整；近华西体系选酒店。',
        tips: '不适勿西行。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Giant_Panda_at_Chengdu.jpg/1280px-Giant_Panda_at_Chengdu.jpg',
      },
      {
        id: 'g318e-kangding',
        name: '康定浅停',
        days: 2,
        pace: 'slow',
        lat: 30.05,
        lng: 101.96,
        summary: '镇区慢走；少剧烈。',
        tips: '供氧与下撤预案。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Mount_Qingcheng.jpg/1280px-Mount_Qingcheng.jpg',
      },
      {
        id: 'g318e-xinduqiao-optional',
        name: '新都桥观景（可选）',
        days: 1,
        pace: 'fast',
        lat: 30.1,
        lng: 101.5,
        summary: '短停拍照即撤；可删过夜。',
        tips: '紫外线强；高反应即返。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Xinduqiao.jpg/1280px-Xinduqiao.jpg',
      },
      {
        id: 'g318e-descend',
        name: '下撤成都',
        days: 1,
        pace: 'fast',
        lat: 30.67,
        lng: 104.06,
        summary: '必须回成都再飞北京。',
        tips: '勿在高原连续加塞。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Giant_Panda_at_Chengdu.jpg/1280px-Giant_Panda_at_Chengdu.jpg',
      },
    ],
  },
  {
    id: 'huadong-jiangnan-water-towns',
    title: '江南水乡 · 乌镇西塘浅住',
    region: 'huadong',
    seasons: ["spring", "autumn"],
    tripType: 'short',
    fromHome: false,
    themes: ["corridor"],
    daysLabel: '约4–6天',
    transport: '北京高铁至杭州/上海转乌镇或西塘；景区摆渡少步行。结束后经杭州或上海高铁回京',
    budgetLabel: '本趟约2200–4000元（高铁+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/1_wuzhen_aerial_2023.jpg/1280px-1_wuzhen_aerial_2023.jpg',
    summary: '江南水乡走廊：乌镇西栅夜景浅逛，西塘或同类水乡二选一；石板防滑、少赶多镇。与苏杭徽长线互补。',
    introduction: '不排周庄乌镇西塘同日特种兵。选一镇连住，另一镇可选日归或删。',
    seasonGuide: '春秋最佳。夏闷热蚊虫；冬湿冷。',
    whyFast: '第二镇可删；只乌镇西栅也成立。',
    notices: [
      '石板路防滑鞋。',
      '夜景人多即早撤。',
      '勿一日三水乡。',
    ],
    researchKeywords: [
      '乌镇 西栅 父母',
      '西塘 慢住',
      '江南水乡 适老',
    ],
    sources: [
      {
        title: 'Wikivoyage：乌镇',
        url: 'https://zh.wikivoyage.org/wiki/%E4%B9%8C%E9%95%87',
        kind: 'other',
        note: '水乡概览，已改写',
      },
    ],
    stops: [
      {
        id: 'jn-hangzhou-gate',
        name: '杭州/上海进出',
        days: 1,
        pace: 'slow',
        lat: 30.27,
        lng: 120.15,
        summary: '枢纽落脚一夜；次日进水乡。',
        tips: '行李少带。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/West_Lake%2C_Hangzhou_2025.jpg/1280px-West_Lake%2C_Hangzhou_2025.jpg',
      },
      {
        id: 'jn-wuzhen',
        name: '乌镇西栅慢住',
        days: 2,
        pace: 'slow',
        lat: 30.74,
        lng: 120.49,
        summary: '镇内慢走；夜景短看。',
        tips: '石板防滑。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/1_wuzhen_aerial_2023.jpg/1280px-1_wuzhen_aerial_2023.jpg',
      },
      {
        id: 'jn-xitang-optional',
        name: '西塘（可选）',
        days: 1,
        pace: 'fast',
        lat: 30.94,
        lng: 120.89,
        summary: '另一水乡浅逛；可删。',
        tips: '勿与乌镇同日。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Bridge_in_Wuzhen_03.JPG/1280px-Bridge_in_Wuzhen_03.JPG',
      },
      {
        id: 'jn-exit',
        name: '枢纽回京',
        days: 1,
        pace: 'fast',
        lat: 30.27,
        lng: 120.15,
        summary: '经杭或沪高铁回京。',
        tips: '预留延误。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/West_Lake%2C_Hangzhou_2025.jpg/1280px-West_Lake%2C_Hangzhou_2025.jpg',
      },
    ],
  },
  {
    id: 'xinan-sichuan-leshan-emei',
    title: '乐山峨眉 · 大佛与金顶浅尝',
    region: 'xinan',
    seasons: ["spring", "autumn"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京飞成都→高铁/车至乐山；峨眉山多用观光车与索道，不硬爬。结束后回成都飞北京',
    budgetLabel: '本趟约2200–4200元（含索道；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Leshan_Giant_Buddha%2C_20161102.jpg/1280px-Leshan_Giant_Buddha%2C_20161102.jpg',
    summary: '川内名山适老浅尝：乐山大佛观光车/舟船减步，峨眉金顶索道量力；不排全山徒步。体健一般者以大佛为主、金顶可删。',
    introduction: '乐山市与峨眉山市。爸妈以乐山城区电梯酒店为锚；金顶低温风大，心脏病/严重高血压建议放弃。',
    seasonGuide: '春秋。冬金顶更冷；夏暑热雷雨。',
    whyFast: '峨眉金顶可整段删；只留乐山大佛。',
    notices: [
      '大佛区观光车优先。',
      '金顶索道与低温；不适即放弃。',
      '回成都再飞京。',
    ],
    researchKeywords: [
      '乐山大佛 观光车 父母',
      '峨眉山 索道 金顶',
      '乐山 慢游',
    ],
    sources: [
      {
        title: 'Wikivoyage：乐山',
        url: 'https://zh.wikivoyage.org/wiki/%E4%B9%90%E5%B1%B1',
        kind: 'other',
        note: '大佛与交通概览，已改写',
      },
    ],
    stops: [
      {
        id: 'le-leshan-base',
        name: '乐山城区慢住',
        days: 2,
        pace: 'slow',
        lat: 29.57,
        lng: 103.76,
        summary: '电梯酒店；抵达休整。',
        tips: '成都高铁或包车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Leshan_Giant_Buddha%2C_20161102.jpg/1280px-Leshan_Giant_Buddha%2C_20161102.jpg',
      },
      {
        id: 'le-giant-buddha',
        name: '乐山大佛（观光）',
        days: 1,
        pace: 'slow',
        lat: 29.54,
        lng: 103.77,
        summary: '观光车/舟船减步；半日。',
        tips: '台阶量力。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Leshan_Giant_Buddha%2C_20161102.jpg/1280px-Leshan_Giant_Buddha%2C_20161102.jpg',
      },
      {
        id: 'le-emei-optional',
        name: '峨眉金顶索道（可选）',
        days: 1,
        pace: 'fast',
        lat: 29.52,
        lng: 103.33,
        summary: '索道上下；短留即撤，可删。',
        tips: '低温厚外套；高反应式不适立即下撤。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Mount_Qingcheng.jpg/1280px-Mount_Qingcheng.jpg',
      },
      {
        id: 'le-back-chengdu',
        name: '返回成都',
        days: 1,
        pace: 'fast',
        lat: 30.67,
        lng: 104.06,
        summary: '成都歇一夜再飞京。',
        tips: '勿当日连飞过劳。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Giant_Panda_at_Chengdu.jpg/1280px-Giant_Panda_at_Chengdu.jpg',
      },
    ],
  },
  {
    id: 'dongbei-heilongjiang-harbin-summer',
    title: '哈尔滨 · 中央大街夏日慢走',
    region: 'dongbei',
    seasons: ["summer", "autumn"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京高铁至哈尔滨约5–6小时，或飞太平；市内地铁/打车。结束后高铁或飞回北京',
    budgetLabel: '本趟约2000–3800元（高铁/机票+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Saint_Sophia_Cathedral_in_Harbin.jpg/1280px-Saint_Sophia_Cathedral_in_Harbin.jpg',
    summary: '哈尔滨夏线补冬雪线：中央大街与索菲亚教堂平地，松花江边散步；不排冰雪大世界。可作五大莲池缓冲。',
    introduction: '哈尔滨市辖道里等。爸妈住中央大街附近电梯酒店；夏日舒适，冬线见独立产品。',
    seasonGuide: '夏秋。冬寒走冰雪线。',
    whyFast: '太阳岛可删；主体中央大街+教堂。',
    notices: [
      '江边风大备外套。',
      '步行石板防滑。',
      '勿与雪乡硬线同趟。',
    ],
    researchKeywords: [
      '哈尔滨 中央大街 夏天',
      '索菲亚教堂',
      '哈尔滨 慢游 父母',
    ],
    sources: [
      {
        title: 'Wikivoyage：哈尔滨',
        url: 'https://zh.wikivoyage.org/wiki/%E5%93%88%E5%B0%94%E6%BB%A7',
        kind: 'other',
        note: '城区概览，已改写',
      },
    ],
    stops: [
      {
        id: 'hrb-daoli-base',
        name: '道里慢住',
        days: 2,
        pace: 'slow',
        lat: 45.77,
        lng: 126.62,
        summary: '近中央大街电梯酒店。',
        tips: '高铁站打车。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Saint_Sophia_Cathedral_in_Harbin.jpg/1280px-Saint_Sophia_Cathedral_in_Harbin.jpg',
      },
      {
        id: 'hrb-central-street',
        name: '中央大街 · 索菲亚',
        days: 1,
        pace: 'slow',
        lat: 45.77,
        lng: 126.63,
        summary: '平地街景与教堂外观/室内。',
        tips: '人多早去。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Saint_Sophia_Cathedral_in_Harbin.jpg/1280px-Saint_Sophia_Cathedral_in_Harbin.jpg',
      },
      {
        id: 'hrb-songhua',
        name: '松花江边浅走',
        days: 1,
        pace: 'slow',
        lat: 45.78,
        lng: 126.62,
        summary: '江畔平路；半日。',
        tips: '风大备外套。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Songhua_River.jpg/1280px-Songhua_River.jpg',
      },
      {
        id: 'hrb-sun-island-optional',
        name: '太阳岛浅览（可选）',
        days: 1,
        pace: 'fast',
        lat: 45.8,
        lng: 126.6,
        summary: '摆渡或桥上观景；可删。',
        tips: '腿脚紧外观即可。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Songhua_River.jpg/1280px-Songhua_River.jpg',
      },
    ],
  },
  {
    id: 'huabei-neimeng-hohhot',
    title: '呼和浩特 · 塞上古城浅住',
    region: 'huabei',
    seasons: ["summer", "autumn"],
    tripType: 'short',
    fromHome: false,
    daysLabel: '约3–5天',
    transport: '北京高铁/飞机至呼和浩特；市区打车。可衔接希拉穆仁草原日归。结束后回京',
    budgetLabel: '本趟约1800–3500元（交通+住宿；双人）',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Hulunbuir.jpg/1280px-Hulunbuir.jpg',
    summary: '内蒙古呼市命名线：市区博物馆与公园慢走，希拉穆仁草原日归可选。与呼伦贝尔长线互补。',
    introduction: '呼和浩特市。爸妈市区电梯酒店为锚；草原日归不过夜也可。',
    seasonGuide: '夏秋。冬寒风大缩短。',
    whyFast: '草原可删；主体市区。',
    notices: [
      '草原日晒强。',
      '乳制品量力。',
      '勿与呼伦贝尔同趟硬赶。',
    ],
    researchKeywords: [
      '呼和浩特 博物馆 父母',
      '希拉穆仁 日归',
      '呼和浩特 慢住',
    ],
    sources: [
      {
        title: 'Wikivoyage：呼和浩特',
        url: 'https://zh.wikivoyage.org/wiki/%E5%91%BC%E5%92%8C%E6%B5%A9%E7%89%B9',
        kind: 'other',
        note: '城区与草原衔接，已改写',
      },
    ],
    stops: [
      {
        id: 'hh-city-base',
        name: '呼市城区慢住',
        days: 2,
        pace: 'slow',
        lat: 40.84,
        lng: 111.75,
        summary: '电梯酒店；抵达休整。',
        tips: '高铁或机场入城。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Hulunbuir.jpg/1280px-Hulunbuir.jpg',
      },
      {
        id: 'hh-museum',
        name: '内蒙古博物院/市区公园',
        days: 1,
        pace: 'slow',
        lat: 40.84,
        lng: 111.74,
        summary: '室内或平路公园择一。',
        tips: '预约以馆方为准。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Hulunbuir.jpg/1280px-Hulunbuir.jpg',
      },
      {
        id: 'hh-xilamuren-optional',
        name: '希拉穆仁草原日归（可选）',
        days: 1,
        pace: 'fast',
        lat: 41.12,
        lng: 111.9,
        summary: '包车日归浅看；可删过夜。',
        tips: '防晒；勿剧烈。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Hulunbuir.jpg/1280px-Hulunbuir.jpg',
      },
      {
        id: 'hh-buffer-optional',
        name: '空白日（可选）',
        days: 1,
        pace: 'fast',
        lat: 40.84,
        lng: 111.75,
        summary: '超市与休息。',
        tips: '可多留。',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Hulunbuir.jpg/1280px-Hulunbuir.jpg',
      },
    ],
  },
];

